p5/config/routes.rb
Rails.application.routes.draw do
# set up 2 routes
  get 'gamestats/search'
  get 'gamestats/index'

# setup the default route to go to the index
  root 'gamestats#index'
 
# setup built-in resources for "gamestats"

  resources :gamestats

end

p5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

p5/app/controllers/gamestats_controller.rb
class GamestatsController < ApplicationController
  def search
	@thetitle = "CHANGEME"
  end

  def index
	@thetitle = "CHANGEME"
  end

  def create
	@thetitle = "CHANGEME"
  end
end

p5/app/helpers/application_helper.rb
module ApplicationHelper
end

p5/app/helpers/gamestats_helper.rb
module GamestatsHelper
end

p5/app/views/gamestats/create.html.erb
<h1>Create Report</h1>

    <%
        require "json"
        scoreFile = "public/Sports.json"

        @formTitle = params[:gamestat][:title]
        @formResult = params[:gamestat][:results]
        @formSearchterm = params[:gamestat][:searchterm]
        %>
        Search parameters:<br>
        <%= @formTitle %>
        <%= @formResult %>
        <%= @formSearchterm %>


	    Start of code here!
		<%
			require "json"
			sportsFile = "public/Sports.json"
		%>

			<%= "Open the file " %>
			<%= sportsFile %>
    <br>
    <%= link_to 'Perform new search', gamestats_search_path %>

p5/app/views/gamestats/index.html.erb
<h1><%= @thetitle %></h1>

Hello!  Welcome to <%= @thetitle %><p>

<%= link_to 'Click to Search', gamestats_search_path %>

p5/app/views/gamestats/search.html.erb
<h1><%= @thetitle %></h1>

Hello!  Welcome to <%= @thetitle %><p>

<p>Find me in app/views/gamestats/search.html.erb</p>
<p>Need to add ERB code to make these drop down menus!</p>
<%= form_for :gamestat, url: gamestats_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </p>
             
    <p>
    <%= f.label :results %><br>
    <%= f.text_field :results %>
    </p>

    <p>
    <%= f.label :searchterm %><br>
    <%= f.text_field :searchterm %>
    </p>
                          
    <p>
        <%= f.submit :Search %>
    </p>
<% end %>

p5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>